using System;
using System.Text.RegularExpressions;
using ColorLib;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ColorLibTest
{
    [TestClass]
    public class TransformWordLists
    {

        //[TestMethod]
        public void CheckVerbesIER()
        {
            //Assert.IsTrue(AutomRuleFilter.verbes_ierACC.IsSubsetOf(AutomRuleFilter.verbes_ierM));
            //foreach (string v in AutomRuleFilter.verbes_ierACC)
            //{
            //    if (!AutomRuleFilter.verbes_ierM.Contains(v))
            //    {
            //        Console.WriteLine(v);
            //    }
            //}
        }

        //[TestMethod]
        public void WriteWords()
        {
            int lPos = 0;
            Regex rx = new Regex(@"\b\w+\b", RegexOptions.Compiled | RegexOptions.IgnoreCase); // matches words
            MatchCollection matches = rx.Matches(words);
            foreach (Match m in matches)
            {
                Console.Write('"');
                Console.Write(m.Value);
                Console.Write("\", ");
                lPos += m.Value.Length + 4;
                if (lPos > 95)
                {
                    Console.WriteLine();
                    lPos = 0;
                }
            }
        }
            
            
        string words =
        @"
            abrier
            abêtifier
            académifier
            académisier
            acidifier
            acétifier
            affier
            affilier
            agatifier
            allier
            amnistier
            amodier
            amplier
            amplifier
            anesthésier
            anémier
            apostasier
            apparier
            approprier
            apprécier
            armorier
            artificier
            asphyxier
            associer
            atrophier
            aurifier
            authentifier
            autographier
            autopsier
            avarier
            balbutier
            barbifier
            baronifier
            biographier
            bistourier
            bonifier
            bougier
            béatifier
            bénéficier
            bêtifier
            calcifier
            calligraphier
            calomnier
            certifier
            charabier
            charrier
            chier
            chirographier
            chosifier
            choséifier
            châtier
            circonstancier
            clarifier
            classifier
            cocufier
            codifier
            colorier
            communier
            complexifier
            conchier
            concilier
            confier
            congédier
            contrarier
            convier
            copier
            corporifier
            crier
            crucifier
            dactylographier
            densifier
            différencier
            différentier
            dignifier
            disgracier
            disqualifier
            dissocier
            diversifier
            domicilier
            domifier
            dulcifier
            décalcifier
            déclassifier
            décrier
            dédier
            dédifférencier
            défier
            déifier
            délier
            démarier
            démultiplier
            démystifier
            démythifier
            dénier
            déparier
            dépatrier
            déplier
            déprécier
            désapproprier
            dévier
            dévitrifier
            ectasier
            enlier
            envier
            escarrifier
            escoffier
            estropier
            estérifier
            excommunier
            excorier
            exemplifier
            exfolier
            expatrier
            expier
            exproprier
            expédier
            extasier
            falsifier
            fantasier
            fier
            fluidifier
            fortifier
            frigorifier
            fructifier
            gambier
            gazéifier
            glorifier
            gracier
            gratifier
            gélifier
            géographier
            harmonier
            historier
            horrifier
            humidifier
            humilier
            hyperplasier
            hypertrophier
            hypostasier
            identifier
            idiotifier
            incendier
            ingénier
            initier
            injurier
            intensifier
            interfolier
            inventorier
            irradier
            justicier
            justifier
            jérémier
            lapidifier
            licencier
            lier
            lignifier
            liquéfier
            lithographier
            lubrifier
            lénifier
            madéfier
            magnifier
            maléficier
            manier
            marier
            massifier
            mellifier
            mendier
            modifier
            mollifier
            momifier
            mondifier
            monographier
            mortifier
            multiplier
            mystifier
            mythifier
            méfier
            mésallier
            nazifier
            nidifier
            nier
            nitrifier
            notifier
            nullifier
            négocier
            obvier
            octavier
            officier
            opacifier
            orthographier
            ossifier
            oublier
            pacifier
            palifier
            palinodier
            pallier
            panifier
            parier
            parodier
            passéifier
            personnifier
            photocopier
            photographier
            pilorier
            plagier
            planchéier
            planifier
            plastifier
            plier
            polycopier
            pontifier
            prier
            privilégier
            prosodier
            préjudicier
            présentifier
            psalmodier
            publier
            purifier
            putréfier
            pépier
            pétrifier
            qualifier
            quantifier
            quintessencier
            radier
            radiographier
            rallier
            ramifier
            rapatrier
            rapparier
            rapproprier
            raréfier
            rassasier
            ratifier
            razzier
            recalcifier
            recopier
            rectifier
            relier
            remanier
            remarier
            remercier
            remplier
            remédier
            renier
            renvier
            replier
            reprographier
            revivifier
            rigidifier
            rubéfier
            russifier
            réconcilier
            récrier
            réexpédier
            réfugier
            réifier
            répertorier
            répudier
            résilier
            résinifier
            réunifier
            réédifier
            saccharifier
            sacrifier
            salarier
            salifier
            sanctifier
            sanguifier
            saponifier
            scarifier
            schistifier
            scier
            scorifier
            sentencier
            signifier
            simplifier
            skier
            solacier
            solfier
            solidifier
            soucier
            spolier
            spécifier
            statufier
            stipendier
            stratifier
            strier
            stupéfier
            sténographier
            substantifier
            supplicier
            supplier
            surmultiplier
            sérier
            tarifier
            terrifier
            tonifier
            torréfier
            transsubstantier
            trier
            tuméfier
            tunisifier
            typifier
            télécopier
            télégraphier
            unifier
            varier
            versifier
            vicarier
            vicier
            vinifier
            vitrifier
            vivifier
            vérifier
            écrier
            édifier
            électrifier
            émacier
            émier
            émulsifier
            épier
            éthérifier
            étudier
            ambroisier
            carier
            défolier
            dragéifier
            gâtifier
            hyperesthésier
            iconographier
            immensifier
            indulgencier
            jazzifier
            lividifier
            lubréfier
            luxurier
            lyrifier
            maladier
            mélancholier
            mélancolier
            mélancolifier
            moruefier
            multigraphier
            nanifier
            négrifier
            nettifier
            noblifier
            odifier
            oedématier
            oursifier
            pécufier
            perlifier
            perruquifier
            phonographier
            plasmifier
            plénifier
            prussifier
            réétudier
            réhumidifier
            renégocier
            réoublier
            reprier
            republier
            revérifier
            rhodier
            sanifier
            savantifier
            sclérifier
            silencier
            starifier
            sublimifier
            sulpicier
            surlier
            syllabifier
            tartufier
            théorifier
            transsubstantifier
            typographier
            alcoolifier
            aluminier
            ammonifier
            analgésier
            angarier
            autenticier
            autocopier
            autodéprécier
            autojustifier
            autolubrifier
            automodifier
            autoradiographier
            autovérifier
            basifier
            bibliographier
            brier
            cadmier
            calorifier
            capier
            caprifier
            carnifier
            cartographier
            caséifier
            caustifier
            chalcographier
            chondrifier
            chorégraphier
            chylifier
            chymifier
            cinégraphier
            cinématographier
            coassocier
            cokéfier
            compactifier
            consonantifier
            consonifier
            copublier
            cosmifier
            covarier
            cryptographier
            cérifier
            diazocopier
            distancier
            déclergifier
            décodifier
            décrucifier
            dédensifier
            dédifférencier
            défortifier
            délignifier
            démassifier
            dénazifier
            dénitrifier
            dépatrier
            déplanifier
            déprier
            dépétrifier
            déqualifier
            dérelier
            dérussifier
            désacidifier
            désaffilier
            désallier
            désapparier
            désassocier
            désertifier
            désessencier
            déshumidifier
            désignifier
            désilicier
            désilicifier
            désirradier
            désorthographier
            désunifier
            désémulsifier
            détoxifier
            dézincifier
            effigier
            entremarier
            escarifier
            escarrifier
            escofier
            euthanasier
            eutrophier
            faséier
            frigidifier
            gabarier
            gleyifier
            graphier
            grésifier
            holographier
            homogénéifier
            houillifier
            humifier
            hyperhémier
            hyperplasier
            hyperémier
            hypolipidémier
            indifférencier
            ingénier
            instancier
            ischémier
            karstifier
            lamifier
            latensifier
            lichénifier
            lignifier
            lithifier
            lithotypographier
            lixivier
            macrophotographier
            magnésier
            matifier
            microcopier
            microphotographier
            miméographier
            moinifier
            muséifier
            méfier
            mésédifier
            neutrographier
            notarier
            olographier
            organifier
            ortier
            pantographier
            peptonifier
            phototélécopier
            polyestérifier
            polygraphier
            potentier
            préplastifier
            prépublier
            présanctifier
            préétudier
            quartzifier
            radioscopier
            radiotélégraphier
            rapprécier
            rebénéficier
            recertifier
            rechâtier
            reclassifier
            recodifier
            recolorier
            reconfier
            recongédier
            recontrarier
            recrier
            redactylographier
            redifférencier
            redomicilier
            redécalcifier
            redédier
            redéfier
            redéplier
            refortifier
            regazéifier
            reglorifier
            relicencier
            relubrifier
            remodifier
            rengracier
            renotifier
            repacifier
            reparier
            rephotocopier
            rephotographier
            replanifier
            replastifier
            requalifier
            resacrifier
            resignifier
            resupplier
            retrier
            retélégraphier
            réaffilier
            réapparier
            réapproprier
            réassocier
            récrier
            réestérifier
            référencier
            réorthographier
            rétifier
            rétrodévier
            scénographier
            silicier
            silicifier
            sismographier
            solmifier
            spathifier
            substantier
            subérifier
            sudorifier
            surqualifier
            sursignifier
            surédifier
            sélénier
            tanguier
            taudifier
            thermoanesthésier
            transestérifier
            tubérifier
            turquifier
            urbanifier
            xylographier
            xérocopier
            xérographier
            échographier
            écrier
            élier
            élutrier
            épigraphier
            épitaxier
            époutier
            équarrier
            étanchéifier
            étatifier
            substancier
            subsidier
            sérigraphier
            saccarifier
            ambifier
            chromolithographier
            compacifier
            décertifier
            décomplexifier
            déplastifier
            dérigidifier
            désidentifier
            glacifier
            grâcier
            hyperqualifier
            interrelier
            piétonnifier
            recrucifier
            redémultiplier
            réapprécier
            sectifier
            téléfalsifier
            zombifier
        ";
    }
}
